language: android
sudo: required
jdk: oraclejdk8
android:
 components:
    - tools
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
before_install:
  - chmod +x gradlew
script:
   - ./gradlew clean build
